// <auto-generated />
using System;
using BackEmpleos.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEmpleos.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251122031829_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.CatalogoEstado", b =>
                {
                    b.Property<byte>("IdEstado")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("ClaveEstado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdEstado");

                    b.ToTable("CatalogoEstadosMx", (string)null);
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailContacto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<byte?>("IdEstado")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("IdUsuarioDueno")
                        .HasColumnType("int");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreLegal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SitioWeb")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tamano")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonoContacto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdUsuarioDueno")
                        .IsUnique();

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.EmpresaSeguida", b =>
                {
                    b.Property<int>("IdEmpresaSeguida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEmpresaSeguida"));

                    b.Property<DateTime>("FechaSeguimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdEmpresaSeguida");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdUsuario");

                    b.ToTable("EmpresasSeguidas", (string)null);
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.OfertaEmpleo", b =>
                {
                    b.Property<int>("IdOferta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOferta"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<byte?>("IdEstado")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("ModalidadTrabajo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("RemotoDesdeCualquierLugar")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("SalarioMax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SalarioMin")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SeniorityRequerido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoContrato")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdOferta");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdEstado");

                    b.ToTable("OfertasEmpleo", (string)null);
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.OfertaFavorita", b =>
                {
                    b.Property<int>("IdOfertaFavorita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOfertaFavorita"));

                    b.Property<DateTime>("FechaGuardado")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdOferta")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdOfertaFavorita");

                    b.HasIndex("IdOferta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("OfertasFavoritas", (string)null);
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.OfertaSkill", b =>
                {
                    b.Property<int>("IdOfertaSkill")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOfertaSkill"));

                    b.Property<bool>("EsDeseable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdOferta")
                        .HasColumnType("int");

                    b.Property<int>("IdSkill")
                        .HasColumnType("int");

                    b.Property<string>("NivelRequerido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdOfertaSkill");

                    b.HasIndex("IdOferta");

                    b.HasIndex("IdSkill");

                    b.ToTable("OfertaSkills", (string)null);
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.PerfilTalento", b =>
                {
                    b.Property<int>("IdPerfilTalento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPerfilTalento"));

                    b.Property<string>("CVUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionPersonal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("DisponibilidadReubicarse")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DisponibilidadViajar")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("ExpectativaSalarialMax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ExpectativaSalarialMin")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ExperienciaTotalAnios")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GithubUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte?>("IdEstado")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ModalidadPreferida")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PortafolioUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TituloProfesional")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdPerfilTalento");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("PerfilesTalento", (string)null);
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.Postulacion", b =>
                {
                    b.Property<int>("IdPostulacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPostulacion"));

                    b.Property<string>("ComentariosCandidato")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ComentariosEmpresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaPostulacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdOferta")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioTalento")
                        .HasColumnType("int");

                    b.HasKey("IdPostulacion");

                    b.HasIndex("IdOferta");

                    b.HasIndex("IdUsuarioTalento");

                    b.ToTable("Postulaciones", (string)null);
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.Skill", b =>
                {
                    b.Property<int>("IdSkill")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSkill"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdSkill");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.UsuarioSkill", b =>
                {
                    b.Property<int>("IdUsuarioSkill")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuarioSkill"));

                    b.Property<decimal>("AniosExperiencia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("IdSkill")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PerfilTalentoIdPerfilTalento")
                        .HasColumnType("int");

                    b.HasKey("IdUsuarioSkill");

                    b.HasIndex("IdSkill");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("PerfilTalentoIdPerfilTalento");

                    b.ToTable("UsuarioSkills", (string)null);
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.Empresa", b =>
                {
                    b.HasOne("BackEmpleos.Api.Models.Entities.CatalogoEstado", "Estado")
                        .WithMany("Empresas")
                        .HasForeignKey("IdEstado");

                    b.HasOne("BackEmpleos.Api.Models.Entities.Usuario", "UsuarioDueno")
                        .WithOne("Empresa")
                        .HasForeignKey("BackEmpleos.Api.Models.Entities.Empresa", "IdUsuarioDueno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("UsuarioDueno");
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.EmpresaSeguida", b =>
                {
                    b.HasOne("BackEmpleos.Api.Models.Entities.Empresa", "Empresa")
                        .WithMany("Seguidores")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEmpleos.Api.Models.Entities.Usuario", "Usuario")
                        .WithMany("EmpresasSeguidas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.OfertaEmpleo", b =>
                {
                    b.HasOne("BackEmpleos.Api.Models.Entities.Empresa", "Empresa")
                        .WithMany("OfertasEmpleo")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEmpleos.Api.Models.Entities.CatalogoEstado", "EstadoMx")
                        .WithMany("OfertasEmpleo")
                        .HasForeignKey("IdEstado");

                    b.Navigation("Empresa");

                    b.Navigation("EstadoMx");
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.OfertaFavorita", b =>
                {
                    b.HasOne("BackEmpleos.Api.Models.Entities.OfertaEmpleo", "OfertaEmpleo")
                        .WithMany("Favoritos")
                        .HasForeignKey("IdOferta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEmpleos.Api.Models.Entities.Usuario", "Usuario")
                        .WithMany("OfertasFavoritas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfertaEmpleo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.OfertaSkill", b =>
                {
                    b.HasOne("BackEmpleos.Api.Models.Entities.OfertaEmpleo", "OfertaEmpleo")
                        .WithMany("OfertaSkills")
                        .HasForeignKey("IdOferta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEmpleos.Api.Models.Entities.Skill", "Skill")
                        .WithMany("OfertaSkills")
                        .HasForeignKey("IdSkill")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfertaEmpleo");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.PerfilTalento", b =>
                {
                    b.HasOne("BackEmpleos.Api.Models.Entities.CatalogoEstado", "Estado")
                        .WithMany("PerfilesTalento")
                        .HasForeignKey("IdEstado");

                    b.HasOne("BackEmpleos.Api.Models.Entities.Usuario", "Usuario")
                        .WithOne("PerfilTalento")
                        .HasForeignKey("BackEmpleos.Api.Models.Entities.PerfilTalento", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.Postulacion", b =>
                {
                    b.HasOne("BackEmpleos.Api.Models.Entities.OfertaEmpleo", "OfertaEmpleo")
                        .WithMany("Postulaciones")
                        .HasForeignKey("IdOferta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEmpleos.Api.Models.Entities.Usuario", "UsuarioTalento")
                        .WithMany("Postulaciones")
                        .HasForeignKey("IdUsuarioTalento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfertaEmpleo");

                    b.Navigation("UsuarioTalento");
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.UsuarioSkill", b =>
                {
                    b.HasOne("BackEmpleos.Api.Models.Entities.Skill", "Skill")
                        .WithMany("UsuarioSkills")
                        .HasForeignKey("IdSkill")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEmpleos.Api.Models.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioSkills")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEmpleos.Api.Models.Entities.PerfilTalento", null)
                        .WithMany("UsuarioSkills")
                        .HasForeignKey("PerfilTalentoIdPerfilTalento");

                    b.Navigation("Skill");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.CatalogoEstado", b =>
                {
                    b.Navigation("Empresas");

                    b.Navigation("OfertasEmpleo");

                    b.Navigation("PerfilesTalento");
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.Empresa", b =>
                {
                    b.Navigation("OfertasEmpleo");

                    b.Navigation("Seguidores");
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.OfertaEmpleo", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("OfertaSkills");

                    b.Navigation("Postulaciones");
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.PerfilTalento", b =>
                {
                    b.Navigation("UsuarioSkills");
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.Skill", b =>
                {
                    b.Navigation("OfertaSkills");

                    b.Navigation("UsuarioSkills");
                });

            modelBuilder.Entity("BackEmpleos.Api.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Empresa")
                        .IsRequired();

                    b.Navigation("EmpresasSeguidas");

                    b.Navigation("OfertasFavoritas");

                    b.Navigation("PerfilTalento")
                        .IsRequired();

                    b.Navigation("Postulaciones");

                    b.Navigation("UsuarioSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
